/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;

import BUS.TaiKhoanBUS;
import DTO.TaiKhoanDTO;
import GUI.Panel.PanelTaiKhoan;
import java.awt.Color;
import javax.swing.JOptionPane;
import util.Func_class;

/**
 *
 * @author kiman
 */
public class CreateTKDialog extends javax.swing.JDialog {
    Func_class func=new Func_class();
    int maNV;
    TaiKhoanBUS tkBus=new TaiKhoanBUS();
    PanelTaiKhoan tkPanel;
    public CreateTKDialog(java.awt.Frame parent, boolean modal,int maNV,PanelTaiKhoan tkPanel) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cấp tài khoản");
        this.tkPanel=tkPanel;
        this.maNV=maNV;
        khoiTao();
    }
    public void khoiTao(){
        setUpBtn();
        setUpJTF();
    }
    public void setUpBtn(){
        func.setUpBtn(btn_save, Color.WHITE, Color.orange);
        func.setUpBtn(btn_huy, Color.WHITE, Color.RED);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int check(){
        if(jtf_tk.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập tài khoản","Error",0);
            return 0;
        }
        if(new String(jtf_pass.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập mật khẩu","Error",0);
            return 0;
        }
        if(new String(jtf_repass.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập lại mật khẩu","Error",0);
            return 0;
        }
        if(!new String(jtf_pass.getPassword()).equals(new String(jtf_repass.getPassword()))){
            JOptionPane.showMessageDialog(null,"Mật khẩu không trùng","Error",0);
            return 0;
        }
        return 1;
    }
    public void setUpJTF(){
        func.setUpJTF(jtf_tk);
        func.setUpJTF(jtf_pass);
        func.setUpJTF(jtf_repass);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_tk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtf_pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jtf_repass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tài khoản");

        jtf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_passActionPerformed(evt);
            }
        });

        jLabel2.setText("Mật khẩu");

        jLabel3.setText("Nhập lại mật khẩu ");

        btn_save.setText("Tạo");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy bỏ");
        btn_huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_huyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtf_tk)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_pass)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_repass, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_save)
                        .addGap(60, 60, 60)
                        .addComponent(btn_huy)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_repass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_passActionPerformed
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (check() == 1) {
            String tkhoan = jtf_tk.getText();
            String mk = new String(jtf_pass.getPassword());
            TaiKhoanDTO tk=new TaiKhoanDTO(maNV,tkhoan,mk,"1");
            tkBus.insertTaiKhoan(tk);
            tkPanel.setUpTable();
            this.dispose();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huyMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_huyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jtf_pass;
    private javax.swing.JPasswordField jtf_repass;
    private javax.swing.JTextField jtf_tk;
    // End of variables declaration//GEN-END:variables
}
